story_parsing_task:
  description: >
    제공된 원본 이야기를 자세히 읽고 분석하세요. 
    전체 내러티브를 주의 깊게 살펴보면서 주요 갈등, 등장인물, 그리고 시작부터 끝까지의 전체적인 흐름을 파악하세요. 
    이야기의 갈등이나 주제의 핵심을 담아 2-3줄로 핵심 줄거리를 요약하세요. 
    다음으로, 이야기의 톤이나 장르를 파악하세요 - 예를 들어, 코믹한지, 감동적인지, 서스펜스가 있는지, 또는 공포스러운지 등을 판단하세요.

    분석하는 동안, 시청자들이 가장 몰입할 수 있는 "임팩트 포인트"를 찾아내세요. 
    예를 들어 놀라운 순간, 웃음을 주는 장면, 또는 감정적 긴장감이 있는 부분 등입니다. 
    또한, 현재 이야기의 결말을 검토하세요. 결말이 해당 장르에 맞게 잘 마무리 되었는지 (코믹 장르라면 웃기게), 결말이 없다면 보완하세요. 결말은 해당 장르에 맞게 자극적이며 사람들의 어그로를 끌 수 있도록 해야합니다. 

    이야기의 시작 부분에도 특별한 관심을 기울여주세요. 
    시청자들이 첫 순간부터 빠져들 수 있도록, 더욱 몰입감 있고 자극적이고 어그로를 끌 수 있는 도입부를 제안해주세요. 
    이는 매력적인 숏폼 비디오를 만들기 위한 토대를 마련하는 것이 목적이므로, 시작 부분의 "훅"과 마지막의 "펀치" 모두에 대한 아이디어가 매우 중요합니다.

    다소 이야기가 자극적이더라도 절대 순화하지 마세요. 

    이제 원본 이야기 입니다: 
    {story}
  expected_output: >
    1. 이야기의 핵심 사건이나 갈등을 2-3줄로 간략하게 요약해주세요.

    2. 이야기의 전체적인 분위기나 장르를 명확하게 알려주세요 (예: 코미디, 드라마, 공포, 스릴러).

    3. 핵심 임팩트 포인트들을 나열해주세요 - 시청자들이 웃음을 터뜨리거나, 놀라거나, 강한 감정적 공감을 느낄 수 있는 특정 순간들을 찾아주세요.

    4. 현재 결말이 마무리가 되어있는지 평가하고 마무리가 되어있지 않다면 마무리를 해주세요. 

    5. 도입부를 몰입감 있게 시청자를 사로잡을 수 있게 만들기 위한 한 두 가지 자연스러운 아이디어를 제안해주세요. 

  agent: scenario_creator

character_background_setup_task: 
  description: >
    이야기의 핵심 등장인물들과 주요 배경을 찾아 다듬어주세요. 
    우선, 등장인물들에게 실제 이름을 쓸지, 아니면 "신입이" "사장님" 같은 역할이나 별명을 쓸지 정해주세요. 
    그리고 각 캐릭터에게 이야기의 재미나 극적인 요소를 살릴 수 있는 독특한 성격이나 특징을 부여해주세요 
    - 예를 들어 항상 실수를 하는 성격이라든가, 겉으로는 무섭지만 속은 따뜻한 사람이라든가 하는 식으로요.

    또한, 이야기의 배경도 확실히 잡아주세요: 시간과 장소를 명확히 하는 거죠. 
    회사가 배경이라면, 어떤 종류의 사무실인지, 어떤 분위기인지, 그리고 특별히 눈에 띄는 세부사항들을 구체적으로 적어주세요 
    (예: "주인공의 첫 출근날 아침, 러시아워로 꽉 찬 지하철에서"). 
    이렇게 하는 목적은 각 캐릭터가 확실히 기억에 남고, 이야기의 배경이 생생하고 구체적이어서, 맥락이 분명하고 이야기의 색깔이 강한 숏폼 비디오로 쉽게 만들 수 있게 하기 위해서입니다.
  
  expected_output: >
    1. 주요 등장인물들의 목록을 작성하되, 실제 이름이나 명확한 직함을 사용하세요 (예: "신입", "김 과장"). 
    각 인물의 성격이나 특징을 간단히 설명해주세요 (독특한 특성, 갈등 요소, 또는 코믹한 잠재력).

    2. 이런 특징들을 숏폼 비디오의 분위기에 맞게 어떻게 살짝 과장하거나 다듬으면 좋을지 구체적으로 메모해주세요.
    
    3. 배경을 확실하게 잡아주세요. 시대 설정(현대인지, 어떤 계절인지), 장소(IT 스타트업 사무실인지, 고등학교인지, 출근 시간 기차역인지), 그리고 이야기 전개에 중요한 세부사항들(첫 출근날인지, 꽉 막힌 출퇴근길인지, 특이한 회사 문화가 있는지)을 포함해주세요.
    
    4. 시청자들이 이야기 속 세계에 더 잘 빠져들 수 있게 해주는 추가적인 배경이나 작은 디테일들도 넣어주세요 (예를 들면 "사무실 커피머신은 늘 고장 나 있다" "학교 복도는 항상 지각생들로 북적인다" 같은 것들).
  
  agent: scenario_creator

story_structure_task: 
  description: >
    시나리오는 “기-승-전-결” 혹은 3막 구조(도입, 전개, 결말)로 명확하게 구성하여 짧은 영상에서도 몰입감을 유지할 수 있도록 한다. 
    도입부(기 혹은 도입)에서는 시청자가 즉시 관심을 가질 수 있는 장면이나 사건을 제시하여 강렬한 첫인상을 남긴다. 

    전개부(승 혹은 중반)에서는 갈등을 심화시키거나 인물 간의 관계를 더욱 극적으로 보여주어, 시청자가 “과연 어떻게 될까?” 하고 계속 집중하게 만든다. 

    결말부는 이전의 스토리 분석 결과를 바탕으로 마무리를 해주세요.

  expected_output: >
    1. 1인칭 시점 서술을 기반으로 내레이션이 주도하는 형태의 시나리오를 구성하며, 시나리오를 “기-승-전-결” 또는 3막 구조(도입, 전개, 결말)로 구분한 간단한 개요.
    
    2. 도입부를 어떻게 꾸며서 시청자를 사로잡을지에 대한 구체적인 아이디어 (예: 강렬한 장면, 궁금증 유발, 감정 이입 등).
    
    3. 중반부에서 갈등이 어떻게 발전되고 긴장감이 어떻게 고조되는지 요약.

    4. 결말 부분에서 이야기의 결말을 마무리 해주세요.
  
  agent: scenario_creator

first_person_scenario_task:
  description: >
    완성된 시나리오 구조를 1인칭 시점으로 '의식의 흐름' 기법(Stream of consciousness) 또는 '자유 연상식 서술' 형태로 서술하는 스토리를 완성한다. 
    
    예시:  "담임 선생님을 꼬셔버렸다. 고3때 젊은 여자썜이 담임이 됐는데 내가 남중 남고를 나오기도 했고, 그 쌤이 예뻐서 좋다는 티를 엄청 내고 다녔어. 오죽하면 다른 쌤들이 너 **썜 너무 좋아하는거 아니야" 
    
    스토리는 화자가 직접 자신의 경험을 풀어내듯 전개되며, 주요 사건이나 감정의 변화를 화자의 말로 전달한다. 
    각 장면(Scene)에서는 화자의 내면 묘사(생각, 감정), 주변 배경, 그리고 등장인물 간 상호작용이 구체적으로 나타나야 한다. 
    시청자는 화자의 내레이션을 통해 상황을 간접 체험하며, 장면 전환이나 사건 전개를 자연스럽게 따라갈 수 있다.

    장면별로 다음 요소를 명시한다:
    - 제목(선택) 또는 번호(Scene #)
    - 장면 요약: 해당 씬에서 벌어지는 핵심 사건, 감정 흐름
    - 배경/장소: 구체적 공간(회사 사무실, 지하철 등)과 그 분위기(바쁜, 긴장된 등)
    - 등장인물(캐릭터): 어떤 역할과 성격을 갖고 있는지
    - 상황 설명 & 주요 포인트: 갈등, 웃음 포인트, 반전, 감정 변화 등
    - 내레이션(1인칭 시점 서술): 이 씬에서 화자가 느끼고 생각하는 바를 직접적인 1인칭 서술 형태로 작성
  
  expected_output: >
    1. 스토리 개요(전체 줄거리와 1인칭 시점의 특징 요약):
       - 화자가 어떤 상황에 처해 있고, 이야기를 통해 무엇을 전하려는지
         간단히 명시.
    2. 장면(Scene)별 구성 정보:
       - Scene # 또는 제목(예: Scene 1 - “낯선 출근 첫날”)
       - 장면 요약(핵심 사건, 감정 흐름)
       - 배경/장소 및 분위기(예: 출근 시간의 붐비는 지하철, 조용한 사무실 등)
       - 등장인물: 캐릭터 이름, 성격, 역할, 화자와의 관계
       - 상황 설명 & 주요 포인트: 갈등, 웃음 포인트, 반전 등
       - 내레이션(1인칭): 
         예) “(당황한 톤) ‘나는 지금 막 출근해보았는데, 이 회사 문화를
         전혀 모르겠어... 사람들 표정에서 긴장감이 느껴진다.’”
    3. 각 장면 사이의 자연스러운 흐름(씬 전환)을 고려한 코멘트:
       - 씬이 어떻게 넘어가는지, 화자가 어떤 심경 변화를 느끼는지
         간략히 언급.
    4. 최종적으로 스토리가 마무리되는 장면(결말)에서의 내레이션:

  agent: scenario_creator

first_person_scenario_enhancement_task:
  description: >
    1인칭 시점으로 작성된 시나리오를 더욱 풍부하고 몰입감 있게 보강한다.
    먼저, 화자의 심리 묘사나 주변 상황에 대한 묘사가 부족한 부분이 있는지 
    점검하고, 필요하다면 구체적인 감정 표현이나 배경 설명을 추가해 화자의 
    시선을 더욱 생생하게 전달한다. 단, 쇼츠 특성상 지나치게 장황한 
    설명보다는 핵심적인 감정이나 행동을 중심으로 임팩트를 살린다.
    
    또한 화자의 내레이션을 통해 개그, 반전, 또는 강렬한 감정 변화를 
    자연스럽게 삽입하여 시나리오 전개가 한층 다이내믹해지도록 한다.
    예를 들어, 화자가 느끼는 사소한 해프닝을 코믹하게 풀어내거나, 
    예고 없이 터지는 반전 상황을 추가해 시청자가 “와, 이런 전개가?”라며 
    놀라게 만드는 것도 좋은 방법이다. 쇼츠에서는 장면 전환 속도가 빠르므로, 
    내레이션이 장면 간 연결 고리 역할을 하도록 주의하며, 리드미컬한 전개를 
    유지해 시청자가 끝까지 흥미를 잃지 않게 구성한다.

  expected_output: >
    1. 보강된 시나리오 개요: 원본 대비 좀 더 풍부해진 화자의 심리 및 
       주변 상황 묘사, 추가된 개그/반전/감정 요소 정리.
    2. 화자가 1인칭으로 느끼는 핵심 감정(두려움, 설렘, 분노, 웃음 등)과 
       그에 따른 행동 변화(말투, 표정, 상황 반응 등) 설명.
    3. 새로 삽입된 또는 개선된 에피소드나 대사(1인칭 내레이션 형태로,
       코믹하거나 반전 요소가 들어간 문장 예시).
    4. 장면 간 전환 시 내레이션으로 어떻게 자연스럽게 이어지는지,
       그리고 쇼츠의 빠른 템포를 살리기 위해 어떤 부분에서 감정이나 
       이벤트의 밀도를 높였는지에 대한 간략한 요약.

  agent: scenario_creator

first_person_scenario_review_task:
  description: >
    보강된 1인칭 시나리오가 전체적으로 논리적이고 일관성이 있는지 점검한다.
    캐릭터가 본인(화자) 중심으로만 움직이거나, 갑작스럽게 행동을 바꾸는 
    부분은 없는지 유의 깊게 살펴본다. 시간 순서가 불합리하게 뒤섞이거나 
    플롯 구멍(plot hole)이 나타나지 않는지도 검토한다.
    
    또한 유튜브 쇼츠 기준으로 약 1분 이내의 분량인지 여부를 다시 한번 
    확인한다. 내레이션이 중심이 되는 시나리오이므로, 실제 낭독했을 때 
    대략적인 시간을 가늠해 보고, 너무 길거나 복잡하게 느껴진다면 어디에서 
    간단히 줄이거나 생략할 수 있는지 판단한다. 이 과정을 통해 최종 시나리오 
    길이를 조정하고, 불필요한 내레이션이나 장면이 있으면 정리함으로써 
    시청자에게 더욱 명료하고 흥미로운 이야기를 전달할 수 있도록 한다.

  expected_output: >
    1. 논리적 일관성 점검 결과: 화자(1인칭 시점)의 시선, 캐릭터 행동 
       당위성, 시간 순서 적절성 및 플롯 구멍 여부.
    2. 1분 이내 낭독을 가정했을 때의 대략적 분량 및 시나리오 전개 
       속도 평가.
    3. 이야기의 압축이나 생략이 필요한 부분(장면, 내레이션, 불필요한 
       설정 등)에 대한 구체적인 제안.
    4. 최종 시나리오 전반에 대한 종합 피드백(무엇을 수정, 삭제, 
       보완하면 좋을지 등).
  agent: scenario_creator

first_person_scenario_finalization_task:
  description: >
    이전 단계에서 리뷰 및 보완을 거친 1인칭 시나리오를 최종 형태로
    완성한다. 이 작업에서는 모든 장면이 일관성 있고, 시간 순서가 정합적이며, 
    쇼츠 영상 제작에 필요한 분량(약 1분 이내)으로 정돈되었는지 다시 한 번 
    점검한 뒤 최종 스크립트를 작성한다. 1인칭 내레이션을 중심으로, 각 장면별 
    핵심 사건, 화자의 감정 표현, 등장인물의 행동, 배경 설명 등이 조화를 
    이루도록 구성한다.

    특히, 쇼츠 제작 후속 단계(예: TTS, AI 이미지 생성, 편집)에서
    바로 활용할 수 있도록 장면(Scene) 단위로 시나리오를 확정한다.
    각 장면에 필요한 내레이션, 캐릭터 간 짧은 대화(필요 시), 중요한
    상황 설명을 명료하게 나열하고, 가능한 한 불필요한 중복을 제거해
    시청자에게 임팩트 있는 스토리를 전달할 수 있게 한다.

  expected_output: >
    1. 최종 확정된 1인칭 시나리오 문서:
       - 장면(Scene)별로 구조화된 내레이션, 상황 요약, 캐릭터 등장 여부,
         배경 묘사 등.
       - 화자의 심리 묘사와 핵심 사건이 자연스럽게 연결되도록 정리된
         텍스트.
    2. 각 장면의 예상 분량(대략적 내레이션 시간), 이후 편집 단계를 
       위한 참고 정보(예: 감정 강조 부분, 전환 시점).
    3. 반영된 수정 사항 및 추가한 요소(개그, 반전, 감정 변화 등)에 대한 
       간단한 코멘트(어떤 의도로 삽입했는지, 어떻게 스토리 흐름을 
       강화하는지).
    4. 최종적으로 1분 이내에 담길 수 있는지 여부 확인(녹음 분량,
       장면 전환 템포 등)과, 필요하다면 아주 짧게 줄일 수 있는 
       옵션(장면 간 소폭 축소 아이디어 등).

  agent: scenario_creator