dramatic_narration_task:
  description: >
    다음 지침에 따라 이야기를 각색해주세요.
    1. 서술 방식
    - 마치 친구에게 직접 이야기하듯 구어체로 서술
    - 현장감 있는 묘사와 생생한 감정 표현 사용
    - 대화문은 ""로 표시 (예: "안녕하세요")
    - 내적 독백은 ''로 표시 (예: '이게 뭐지?')
    - 상황 설명은 ~했어, ~였어 등 친근한 과거형 사용
    - 첫 문장 작성 규칙: 임팩트 있는 한 줄 요약으로 시작 (e.g "여자친구가 두 명이 됐다", "담임선생님을 꼬셔버렸다.")

    2. 이야기 구조
    - 상황 설정: 언제, 어디서, 누구와 있었는지 구체적으로 시작
    - 사건 전개: 주인공의 내적 감정과 의도를 포함하여 자연스럽고 긴장이 끊이지 않게 리드미컬하게 전개
    - 핵심 장면: 가장 극적인 순간을 자세하게 묘사
    - 결말: 그 순간 이후의 변화나 영향을 포함

    3. 감정선 표현
    - 주인공의 심리 변화를 내적 독백으로 자연스럽게 표현
    - 다른 등장인물들의 반응도 구체적으로 묘사
    - 유머러스한 요소나 반전을 적절히 활용

    4. 현장감 있는 디테일
    - 소리, 동작, 표정 등을 구체적으로 묘사
    - 시간의 흐름을 잘 보여주는 전개
    - 등장인물들의 생생한 반응 포함

    5. 결말 처리
    - 단순한 마무리 대신 반전/후일담으로 이야기를 승화
    - 장르(유머/흑역사)에 맞는 재미 요소 추가
    - 등장인물들의 변화나 깨달음을 유머러스하게 표현
    - 현재와 과거를 연결하는 아이러니한 상황 활용
    - 이야기의 교훈이나 반전을 재치있게 녹여내기

    예시 결말 패턴:
    1) 역전 패턴: 불행한 상황이 오히려 긍정적 결과를 가져옴
    2) 반복 패턴: 비슷한 상황이 다른 맥락에서 재미있게 반복
    3) 아이러니 패턴: 피하려했던 상황이 더 크게 돌아옴
    4) 교훈 패턴: 웃픈 경험이 나중에 도움이 됨
    5) 연결 패턴: 현재 상황과 과거가 예상치 못한 방식으로 연결

    다음 <example_story_N> 태그들에 있는 이야기를 예시로 참고하면 돼. 
    
    <example_story_1>
      <title> 여친이 복사되는 마법 </title>
      <content> 여자친구가 두 명이 됐다. 와이프가 연애 초반에 자기 언니랑 자취했거든 근데 하루는 “언니가 오빠 궁금하다는데 우리집에 놀러올래?” (대사가 필요한 부분은 “”로 강조) “난 당연히 좋지” 가족분들 중에 처음으로 뵙는거라서 전날에 정장까지 다려놨어. 약속 당일날 과일 사들고 가니까 와이프가 현관문 열어주는데 “오빠 빨리 왔네” 과일 바구니만 넘겨주고 화장실에서 손씻고 나오니까 와이프가 부엌에서 과일을 씻고 있는거야 ‘자기 옷 갈아입었네..?’ (내적 독백은 ‘’ 로 강조) 뒤에서 백허그를 하는 순간 “꺅!!” “왜!!” “뭐야?” 와이프가 내 뒤에서 뛰어오는데 그럼 내가 백허그한 사람은..? 맞아.. 우리 처형이었어. 와이프랑 처형이 일란성 쌍둥인데 헤어스타일도 비슷해서 뒤에서 보면 구분이 안돼 “죄송합니다 00인줄 알았어요” “괜찮아요 저희 부모님도 헷갈려하세요” 처형과의 첫만남은 진짜 흑역사였어. 와이프랑 결혼하고 나서도 처형이랑 같이 술마실때면 제부한테 백허그도 받고 가문의 영광이야” “그만 놀리세요 부끄러워잉” </content< 
    </example_story_2>

    <exmaple_stroy_2> 
      <title> 선생님, 이젠 자기라고 부를게. </title>
      <content> 담임선생님을 꼬셔버렸다. 고3 때 젊은 여자쌤이 담임이 됐는데 내가 남중 남고를 나오기도 했고 그 쌤이 예뻐서 좋다는 티를 엄청 내고다녔어. 오죽하면 다른 쌤들이 "너 00쌤 너무 좋아하는거 아니야?"" 물론 그 선생님은 내가 부담스러우니까 선은 지켜줬으면 좋겠다. 그 말 들은 이후론 나도 반포기 상태로 조용하게 학교다녔지 그렇게 졸업을 하고 바로 군대갔다가 대구에서 취직을 했어. 근데 친구들한테 선생님 소식 들어보니까 대구로 학교를 옮기셨다고 하더라고 선생님에 대한 감정도 사라졌고 그냥 그분이 잘 지내시나 싶어서 톡을 보냈다. “선생님 저 기억하세요?” 근데 어쩌다보니 그 선생님이랑 밥을 먹게 된거야 토요일 점심에 약속장소에서 기다리는데 “00아 잘 지냈어?” 선생님 보는 순간 심장이 쿵 내려앉더라 그날부터 내 짝사랑은 다시 시작됐어 주말마다 밥 먹자고 꼬시고 퇴근할 때 데리러가고 나 진짜 많이 노력했거든 결국엔 선생님이랑 사귀고있다 ㅋㅋ 이젠 선생님 아니고 자기라고 불러 6살 연상이지만 너무 귀엽다 </content> 
    </example_story_2>

    원본 이야기: {story}

  expected_output: >
    <example_story> 태그에 있는 이야기처럼 작성해주면 됩니다.
  
  agent: scenario_creator

feedback_task: 
  description: >
    유튜브 쇼츠에 담길 다음 작성된 초안 스토리를 자연스럽게 

    피드백은 개선 방향과 실행 가능성이 담긴 구체적인 피드백으로 작성해주세요. 
    
  expected_output: >
    작성된 초안 스토리에 대한 개선 방향과 실행 가능성이 담긴 구체적인 피드백을 작성해주세요.
  
  agent: story_analysis_and_growth_enhancement_agent


refinement_task:
  description: >
    받은 피드백을 참고해 만들어진 초안 스토리를 개선해주세요.

    스토리의 어조나 스타일은 이전처럼 유지해주세요. 

    다음 <example_story_N> 태그들에 있는 이야기를 예시로 참고하면 돼. 
    
    <example_story_1>
      <title> 여친이 복사되는 마법 </title>
      <content> 여자친구가 두 명이 됐다. 와이프가 연애 초반에 자기 언니랑 자취했거든 근데 하루는 “언니가 오빠 궁금하다는데 우리집에 놀러올래?” (대사가 필요한 부분은 “”로 강조) “난 당연히 좋지” 가족분들 중에 처음으로 뵙는거라서 전날에 정장까지 다려놨어. 약속 당일날 과일 사들고 가니까 와이프가 현관문 열어주는데 “오빠 빨리 왔네” 과일 바구니만 넘겨주고 화장실에서 손씻고 나오니까 와이프가 부엌에서 과일을 씻고 있는거야 ‘자기 옷 갈아입었네..?’ (내적 독백은 ‘’ 로 강조) 뒤에서 백허그를 하는 순간 “꺅!!” “왜!!” “뭐야?” 와이프가 내 뒤에서 뛰어오는데 그럼 내가 백허그한 사람은..? 맞아.. 우리 처형이었어. 와이프랑 처형이 일란성 쌍둥인데 헤어스타일도 비슷해서 뒤에서 보면 구분이 안돼 “죄송합니다 00인줄 알았어요” “괜찮아요 저희 부모님도 헷갈려하세요” 처형과의 첫만남은 진짜 흑역사였어. 와이프랑 결혼하고 나서도 처형이랑 같이 술마실때면 제부한테 백허그도 받고 가문의 영광이야” “그만 놀리세요 부끄러워잉” </content< 
    </example_story_2>

    <exmaple_stroy_2> 
      <title> 선생님, 이젠 자기라고 부를게. </title>
      <content> 담임선생님을 꼬셔버렸다. 고3 때 젊은 여자쌤이 담임이 됐는데 내가 남중 남고를 나오기도 했고 그 쌤이 예뻐서 좋다는 티를 엄청 내고다녔어. 오죽하면 다른 쌤들이 "너 00쌤 너무 좋아하는거 아니야?"" 물론 그 선생님은 내가 부담스러우니까 선은 지켜줬으면 좋겠다. 그 말 들은 이후론 나도 반포기 상태로 조용하게 학교다녔지 그렇게 졸업을 하고 바로 군대갔다가 대구에서 취직을 했어. 근데 친구들한테 선생님 소식 들어보니까 대구로 학교를 옮기셨다고 하더라고 선생님에 대한 감정도 사라졌고 그냥 그분이 잘 지내시나 싶어서 톡을 보냈다. “선생님 저 기억하세요?” 근데 어쩌다보니 그 선생님이랑 밥을 먹게 된거야 토요일 점심에 약속장소에서 기다리는데 “00아 잘 지냈어?” 선생님 보는 순간 심장이 쿵 내려앉더라 그날부터 내 짝사랑은 다시 시작됐어 주말마다 밥 먹자고 꼬시고 퇴근할 때 데리러가고 나 진짜 많이 노력했거든 결국엔 선생님이랑 사귀고있다 ㅋㅋ 이젠 선생님 아니고 자기라고 불러 6살 연상이지만 너무 귀엽다 </content> 
    </example_story_2>
  
  expected_output: >
    피드백을 바탕으로 개선된 스토리 
  
  agent: story_polishing_and_improvement_navigator